### ISSUE TITLE
Possible divergence

### ISSUE THREAD

**Issue by natefaubion** [coot/zephyr#14]
I tried running zephyr on the Spork todo-mvc example https://github.com/natefaubion/purescript-spork/blob/master/package.json#L6

```
yarn example:todo-mvc -- -- -g corefn
...
zephyr Todo.Main.main
```

And zephyr ate up about 30min of CPU time across 6 cores, after which I killed it. It seems unlikely that it was doing productive work for that amount of time.

**Comment by natefaubion** [comment]
I verified that calling that indeed builds the corefn files as requested.

**Comment by natefaubion** [comment]
Actual build command `purs compile -g corefn "bower_components/*/src/**/*.purs" "src/**/*.purs" "examples/todo-mvc/**/*.purs"`

**Comment by natefaubion** [comment]
I tried leaving it running, and it ended up quitting on it's own while logging `Killed: 9`.

**Comment by coot** [comment]
Thanks @natefaubion!

**Comment by coot** [comment]
@natefaubion it's fixed in master; I tried it on the spork todo-mvc, and it runs without diverging.
