### ISSUE TITLE
Issue new release for Zephyr built with PureScript 0.13.x

### ISSUE THREAD

**Issue by thomashoneyman** [coot/zephyr#23]
At work we use Zephyr built from source with PureScript 0.13.3 (after #21 landed) and it works fine with files compiled with other PureScript 0.13.x versions.

However, I recently switched us over to use the Zephyr which is [included in easy-purescript-nix](https://github.com/justinwoo/easy-purescript-nix), which is the last release: 0.2.1. Running this version on a project compiled with PureScript 0.13.6 on Linux causes this error:

```
zephyr: dce-output/Web.Fetch.Integrity/externs.json: openBinaryFile: does not exist (No such file or directory)
```

I put together a [reproduction of most of our PureScript dependencies](https://github.com/th-repro/zephyr), which uses version 0.13.6 of the compiler and version 0.2.1 of Zephyr. But this reproduction fails when compiled and run on Mac OS with a different error:

```
zephyr: output/Web.HTML.HTMLTableHeaderCellElement/corefn.json: openBinaryFile: resource exhausted (Too many open files)
```

This is despite setting a large upper limit on file handles on Mac OS, as described in #9.

I _think_ these errors are red herrings and that projects running on 0.13.x ought to use versions of Zephyr compiled with PureScript 0.13.x. I have been having trouble updating the reproduction to compile Zephyr from source on the master branch using PureScript 0.13.3, but I'll test that out tomorrow and make an update here.

That said: I believe it's worth making a new release compiled with PureScript 0.13.3 which could be added to easy-purescript-nix for everyone to use, regardless of whether I can fully reproduce this issue outside our codebase here.

**Comment by thomashoneyman** [comment]
Well, I've been able to run this on a NixOS machine now and the build succeeds. So I don't know what's going on -- I suppose 0.2.1 _does_ work fine on a project compiled with PureScript 0.13.6 and there must be something else strange going on with our build. I'm going to close this with that in mind.

**Comment by thomashoneyman** [comment]
I've been able to verify that the error in which a directory is not created before the `externs.json` file is written to it (the first error listed above) does disappear so long as the PureScript version used is 0.13+. I'm not entirely sure _why_, but the error does disappear so long as the current Zephyr on master is used.

With that in mind, @coot are you open to making a new release from the current master which includes the resulting static executable?

**Comment by coot** [comment]
Yes, making a new release is an option if this helps.

**Comment by thomashoneyman** [comment]
If you don’t mind kicking that off, I’d appreciate it! And I can add that to easy-purescript-nix from there. Thanks!

**Comment by coot** [comment]
I don't mind, I'll need a few days for that.

**Comment by coot** [comment]
new release: https://github.com/coot/zephyr/releases/tag/v0.2.2

**Comment by thomashoneyman** [comment]
Thanks!
