### ISSUE TITLE
"zephyr: output/Affjax/externs.json: openBinaryFile: does not exist" with purescript 0.13.8

### ISSUE THREAD

**Issue by srghma** [coot/zephyr#38]
https://github.com/thomashoneyman/purescript-halogen-realworld/issues/65

**Comment by srghma** [comment]
zephyr version 0.2.2

https://github.com/srghma/easy-purescript-nix-automatic/blob/master/zephyr/revision.json

**Comment by thomashoneyman** [comment]
See #33, #36 as well as https://github.com/thomashoneyman/purescript-halogen-realworld/pull/64

**Comment by thomashoneyman** [comment]
That said, if things look good with 0.13.8 is it possible to do a new release? @coot

**Comment by coot** [comment]
Before making a new version I need to fix CI (#39)
