### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Mateiadrielrafael** [coot/zephyr#50]
Simply running 
```sh
purs compile --codegen corefn (spago sources)
zephyr Main
``` 
gives me this error:

```sh
zephyr: output/Affjax/foreign.js: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:openBinaryFile: does not exist (No such file or directory)
```

**Comment by coot** [comment]
Which version of `zephyr` and which version of `purescript` are you using?

**Comment by Mateiadrielrafael** [comment]
@coot 
```sh
adrielus@nixos ~> purs --version
0.13.8
adrielus@nixos ~> zephyr --version
0.3.1
```

**Comment by coot** [comment]
I think one needs to use `purs -g corefn,js` as opposed to `purs -g corefn` for PureScript to copy foreign modules to `output` directory.  Does this help?

**Comment by coot** [comment]
Could you try the branch #51, it should fix it without the need to use `-g js` (you'll need to delete `output` directory first).

**Comment by Mateiadrielrafael** [comment]
I cannot try #51 since I use [easy-purescript-nix](https://github.com/justinwoo/easy-purescript-nix). I will try to use corefn,js and see if that works

**Comment by Mateiadrielrafael** [comment]
yep, it worked, reduced my bundle from 2.78mb to 2.03mb, still way too big but so I'll try reducing it some more.

**Comment by coot** [comment]
Have you tried `zephyr -ef Main`?

**Comment by coot** [comment]
I pushed a new release; it should work without generating javascript.
