### ISSUE TITLE
Sometimes produces more code than just bundle-app alone

### ISSUE THREAD

**Issue by milesfrain** [coot/zephyr#57]
I was surprised to see that using zephyr can sometimes increase bundle sizes. Is there a mistake in my workflow?

|| index.js | `parcel` minified
| --- | :---: | :---: |
Just `bundle-app` | 316K | 128K
With `zephyr` | 332K | 132K

``` bash
git clone https://github.com/purescript-halogen/purescript-halogen-template.git bundle-test
cd bundle-test

# Workflow with just spago bundle-app and parcel (no zephyr)

npm run build-prod
du -hs prod/index.js dist/prod.*.js
# 316K    prod/index.js          # bundle-app output
# 128K    dist/prod.0a4f58ae.js  # minified by parcel

# Including zephyr

rm -r dist
spago build --purs-args '--codegen js,corefn' && zephyr Main.main --dce-foreign
purs bundle -o prod/index.js -m Main dce-output/**/*.js
parcel build prod/index.html
du -hs prod/index.js dist/prod.*.js
# 332K    prod/index.js          # zephyr + bundle-app output
# 132K    dist/prod.08b89072.js  # minified by parcel
```

https://discourse.purescript.org/t/recommended-tooling-for-purescript-in-2020/1615/4

**Comment by coot** [comment]
That's rather surprising, is there anything interesting in the diff of both `prod/index.js` files?

**Comment by coot** [comment]
You could also try `zephyr -fe Main.main`.  `zephyr` might be more conservative than `purs bundle` when doing dead code elimination of foreign modules, but that's just my guess.

**Comment by milesfrain** [comment]
Collected some more data in https://discourse.purescript.org/t/recommended-tooling-for-purescript-in-2020/1615/8

The conclusion is that the best results are achieved with `zephyr` when bypassing `purs bundle`, and letting another tool, such as `parcel` make another pass at tree shaking.

**Comment by coot** [comment]
Thanks for the research.
