### ISSUE TITLE
CI: add-path was deprecated

### ISSUE THREAD

**Issue by andys8** [coot/zephyr#59]
`add-path` was deprecated today.

https://github.com/coot/zephyr/blob/4aa399b9055266e8ef463687b491979f468bcd93/.github/workflows/posix.yml#L21

Needs to be replaced with this syntax.

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

```
echo "action_state=yellow" >> $GITHUB_ENV
```

**Comment by coot** [comment]
Will this also work on `Windows`?

**Comment by andys8** [comment]
This seems to be a good answer to the question:

https://github.community/t/environmental-files-on-windows/137631/2

**Comment by coot** [comment]
Fixed in #60
